<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\SearchDB.Application\SearchDB.Application.csproj" />
    <ProjectReference Include="..\SearchDB.SeedData\SearchDB.SeedData.csproj" />
  </ItemGroup>
</Project>
