using Domain;

namespace SearchDB.SeedData;

public static class DemoRecords
{
    public static IReadOnlyList<Product> Products { get; } =
    [
        new(Id(1), "SKU-001", "SmartPhone X1", "Catalog", "SmartPhone X1", 10m, "USD", true),
        new(Id(2), "SKU-002", "UltraBook Pro", "Catalog", "UltraBook Pro", 11m, "USD", true),
        new(Id(3), "SKU-003", "Wireless Earbuds", "Catalog", "Wireless Earbuds", 12m, "USD", true),
        new(Id(4), "SKU-004", "SmartWatch Plus", "Catalog", "SmartWatch Plus", 13m, "USD", true),
        new(Id(5), "SKU-005", "PowerBank 20K", "Catalog", "PowerBank 20K", 14m, "USD", true),
        new(Id(6), "SKU-006", "Bluetooth Speaker", "Catalog", "Bluetooth Speaker", 15m, "USD", true),
        new(Id(7), "SKU-007", "Gaming Mouse", "Catalog", "Gaming Mouse", 16m, "USD", true),
        new(Id(8), "SKU-008", "Mechanical Keyboard", "Catalog", "Mechanical Keyboard", 17m, "USD", true),
        new(Id(9), "SKU-009", "4K Monitor", "Catalog", "4K Monitor", 18m, "USD", true),
        new(Id(10), "SKU-010", "USB-C Hub", "Catalog", "USB-C Hub", 19m, "USD", true),
        new(Id(11), "SKU-011", "Portable SSD", "Catalog", "Portable SSD", 20m, "USD", true),
        new(Id(12), "SKU-012", "Wireless Charger", "Catalog", "Wireless Charger", 21m, "USD", true),
        new(Id(13), "SKU-013", "Laptop Stand", "Catalog", "Laptop Stand", 22m, "USD", true),
        new(Id(14), "SKU-014", "Webcam Pro", "Catalog", "Webcam Pro", 23m, "USD", true),
        new(Id(15), "SKU-015", "Noise Cancelling Headphones", "Catalog", "Noise Cancelling Headphones", 24m, "USD", true),
        new(Id(16), "SKU-016", "Smart LED Bulb", "Catalog", "Smart LED Bulb", 25m, "USD", true),
        new(Id(17), "SKU-017", "Robot Vacuum", "Catalog", "Robot Vacuum", 26m, "USD", true),
        new(Id(18), "SKU-018", "Air Purifier", "Catalog", "Air Purifier", 27m, "USD", true),
        new(Id(19), "SKU-019", "Electric Kettle", "Catalog", "Electric Kettle", 28m, "USD", true),
        new(Id(20), "SKU-020", "Coffee Maker", "Catalog", "Coffee Maker", 29m, "USD", true),
        new(Id(21), "SKU-021", "Blender Pro", "Catalog", "Blender Pro", 30m, "USD", true),
        new(Id(22), "SKU-022", "Toaster Classic", "Catalog", "Toaster Classic", 31m, "USD", true),
        new(Id(23), "SKU-023", "Air Fryer Max", "Catalog", "Air Fryer Max", 32m, "USD", true),
        new(Id(24), "SKU-024", "Rice Cooker", "Catalog", "Rice Cooker", 33m, "USD", true),
        new(Id(25), "SKU-025", "Food Processor", "Catalog", "Food Processor", 34m, "USD", true),
        new(Id(26), "SKU-026", "Electric Grill", "Catalog", "Electric Grill", 35m, "USD", true),
        new(Id(27), "SKU-027", "Water Filter", "Catalog", "Water Filter", 36m, "USD", true),
        new(Id(28), "SKU-028", "Smart Thermostat", "Catalog", "Smart Thermostat", 37m, "USD", true),
        new(Id(29), "SKU-029", "Desk Lamp", "Catalog", "Desk Lamp", 38m, "USD", true),
        new(Id(30), "SKU-030", "Floor Lamp", "Catalog", "Floor Lamp", 39m, "USD", true),
        new(Id(31), "SKU-031", "Office Chair", "Catalog", "Office Chair", 40m, "USD", true),
        new(Id(32), "SKU-032", "Standing Desk", "Catalog", "Standing Desk", 41m, "USD", true),
        new(Id(33), "SKU-033", "Bookshelf Classic", "Catalog", "Bookshelf Classic", 42m, "USD", true),
        new(Id(34), "SKU-034", "Storage Cabinet", "Catalog", "Storage Cabinet", 43m, "USD", true),
        new(Id(35), "SKU-035", "Coffee Table", "Catalog", "Coffee Table", 44m, "USD", true),
        new(Id(36), "SKU-036", "Bedside Table", "Catalog", "Bedside Table", 45m, "USD", true),
        new(Id(37), "SKU-037", "Dining Chair", "Catalog", "Dining Chair", 46m, "USD", true),
        new(Id(38), "SKU-038", "Sofa Comfort", "Catalog", "Sofa Comfort", 47m, "USD", true),
        new(Id(39), "SKU-039", "Memory Foam Pillow", "Catalog", "Memory Foam Pillow", 48m, "USD", true),
        new(Id(40), "SKU-040", "Weighted Blanket", "Catalog", "Weighted Blanket", 49m, "USD", true),
        new(Id(41), "SKU-041", "Travel Backpack", "Catalog", "Travel Backpack", 50m, "USD", true),
        new(Id(42), "SKU-042", "Leather Wallet", "Catalog", "Leather Wallet", 51m, "USD", true),
        new(Id(43), "SKU-043", "Running Shoes", "Catalog", "Running Shoes", 52m, "USD", true),
        new(Id(44), "SKU-044", "Casual Sneakers", "Catalog", "Casual Sneakers", 53m, "USD", true),
        new(Id(45), "SKU-045", "Winter Jacket", "Catalog", "Winter Jacket", 54m, "USD", true),
        new(Id(46), "SKU-046", "Cotton T-Shirt", "Catalog", "Cotton T-Shirt", 55m, "USD", true),
        new(Id(47), "SKU-047", "Denim Jeans", "Catalog", "Denim Jeans", 56m, "USD", true),
        new(Id(48), "SKU-048", "Sports Shorts", "Catalog", "Sports Shorts", 57m, "USD", true),
        new(Id(49), "SKU-049", "Leather Belt", "Catalog", "Leather Belt", 58m, "USD", true),
        new(Id(50), "SKU-050", "Classic Sunglasses", "Catalog", "Classic Sunglasses", 59m, "USD", true),
        new(Id(51), "SKU-051", "Stainless Steel Bottle", "Catalog", "Stainless Steel Bottle", 60m, "USD", true),
        new(Id(52), "SKU-052", "Travel Mug", "Catalog", "Travel Mug", 61m, "USD", true),
        new(Id(53), "SKU-053", "Lunch Box", "Catalog", "Lunch Box", 62m, "USD", true),
        new(Id(54), "SKU-054", "Kitchen Knife Set", "Catalog", "Kitchen Knife Set", 63m, "USD", true),
        new(Id(55), "SKU-055", "Cutting Board", "Catalog", "Cutting Board", 64m, "USD", true),
        new(Id(56), "SKU-056", "Ceramic Plate Set", "Catalog", "Ceramic Plate Set", 65m, "USD", true),
        new(Id(57), "SKU-057", "Glass Storage Set", "Catalog", "Glass Storage Set", 66m, "USD", true),
        new(Id(58), "SKU-058", "Nonstick Pan", "Catalog", "Nonstick Pan", 67m, "USD", true),
        new(Id(59), "SKU-059", "Cast Iron Skillet", "Catalog", "Cast Iron Skillet", 68m, "USD", true),
        new(Id(60), "SKU-060", "Spice Organizer", "Catalog", "Spice Organizer", 69m, "USD", true),
        new(Id(61), "SKU-061", "Yoga Mat", "Catalog", "Yoga Mat", 70m, "USD", true),
        new(Id(62), "SKU-062", "Resistance Bands", "Catalog", "Resistance Bands", 71m, "USD", true),
        new(Id(63), "SKU-063", "Dumbbell Set", "Catalog", "Dumbbell Set", 72m, "USD", true),
        new(Id(64), "SKU-064", "Fitness Tracker", "Catalog", "Fitness Tracker", 73m, "USD", true),
        new(Id(65), "SKU-065", "Running Watch", "Catalog", "Running Watch", 74m, "USD", true),
        new(Id(66), "SKU-066", "Camping Tent", "Catalog", "Camping Tent", 75m, "USD", true),
        new(Id(67), "SKU-067", "Sleeping Bag", "Catalog", "Sleeping Bag", 76m, "USD", true),
        new(Id(68), "SKU-068", "Hiking Backpack", "Catalog", "Hiking Backpack", 77m, "USD", true),
        new(Id(69), "SKU-069", "Portable Stove", "Catalog", "Portable Stove", 78m, "USD", true),
        new(Id(70), "SKU-070", "Camping Lantern", "Catalog", "Camping Lantern", 79m, "USD", true),
        new(Id(71), "SKU-071", "Car Phone Holder", "Catalog", "Car Phone Holder", 80m, "USD", true),
        new(Id(72), "SKU-072", "Tire Inflator", "Catalog", "Tire Inflator", 81m, "USD", true),
        new(Id(73), "SKU-073", "Car Vacuum", "Catalog", "Car Vacuum", 82m, "USD", true),
        new(Id(74), "SKU-074", "Dash Camera", "Catalog", "Dash Camera", 83m, "USD", true),
        new(Id(75), "SKU-075", "Seat Organizer", "Catalog", "Seat Organizer", 84m, "USD", true),
        new(Id(76), "SKU-076", "Car Air Purifier", "Catalog", "Car Air Purifier", 85m, "USD", true),
        new(Id(77), "SKU-077", "LED Headlights", "Catalog", "LED Headlights", 86m, "USD", true),
        new(Id(78), "SKU-078", "Motorcycle Helmet", "Catalog", "Motorcycle Helmet", 87m, "USD", true),
        new(Id(79), "SKU-079", "Bike Lock", "Catalog", "Bike Lock", 88m, "USD", true),
        new(Id(80), "SKU-080", "Bicycle Pump", "Catalog", "Bicycle Pump", 89m, "USD", true),
        new(Id(81), "SKU-081", "Garden Hose", "Catalog", "Garden Hose", 90m, "USD", true),
        new(Id(82), "SKU-082", "Electric Lawn Mower", "Catalog", "Electric Lawn Mower", 91m, "USD", true),
        new(Id(83), "SKU-083", "Plant Pot Set", "Catalog", "Plant Pot Set", 92m, "USD", true),
        new(Id(84), "SKU-084", "Garden Tools Kit", "Catalog", "Garden Tools Kit", 93m, "USD", true),
        new(Id(85), "SKU-085", "Outdoor Chair", "Catalog", "Outdoor Chair", 94m, "USD", true),
        new(Id(86), "SKU-086", "Picnic Table", "Catalog", "Picnic Table", 95m, "USD", true),
        new(Id(87), "SKU-087", "Solar Lantern", "Catalog", "Solar Lantern", 96m, "USD", true),
        new(Id(88), "SKU-088", "Security Camera", "Catalog", "Security Camera", 97m, "USD", true),
        new(Id(89), "SKU-089", "Smart Doorbell", "Catalog", "Smart Doorbell", 98m, "USD", true),
        new(Id(90), "SKU-090", "Digital Door Lock", "Catalog", "Digital Door Lock", 99m, "USD", true),
        new(Id(91), "SKU-091", "First Aid Kit", "Catalog", "First Aid Kit", 100m, "USD", true),
        new(Id(92), "SKU-092", "Travel Organizer", "Catalog", "Travel Organizer", 101m, "USD", true),
        new(Id(93), "SKU-093", "Passport Holder", "Catalog", "Passport Holder", 102m, "USD", true),
        new(Id(94), "SKU-094", "Luggage Set", "Catalog", "Luggage Set", 103m, "USD", true),
        new(Id(95), "SKU-095", "Umbrella Pro", "Catalog", "Umbrella Pro", 104m, "USD", true),
        new(Id(96), "SKU-096", "Portable Fan", "Catalog", "Portable Fan", 105m, "USD", true),
        new(Id(97), "SKU-097", "Mini Projector", "Catalog", "Mini Projector", 106m, "USD", true),
        new(Id(98), "SKU-098", "Bluetooth Tracker", "Catalog", "Bluetooth Tracker", 107m, "USD", true),
        new(Id(99), "SKU-099", "Universal Remote", "Catalog", "Universal Remote", 108m, "USD", true),
        new(Id(100), "SKU-100", "Smart Home Hub", "Catalog", "Smart Home Hub", 109m, "USD", true)
    ];


    private static Guid Id(int value) => Guid.Parse($"00000000-0000-0000-0000-{value:000000000000}");
}
